### ISSUE TITLE
Knapsack incompatible with Glimpse.

### ISSUE THREAD

**Issue by darran** [andrewdavey/knapsack#16]
It seems that knapsack interferes with glimpse or I don't know the correct knapsack config!. (http://getglimpse.com/)

To repro:
1. New MVC3 project. 
2. Use Nuget to install Glimpse MVC3
3. Ensure Glimpse running OK
4. Set Project to use IIS Express
   --> Run website in Debugger - Glimpse works OK
5. Use Nuget to install Knapsack
   --> Run website in debugger - Glimpse doesn't work. Blank screen shown in browser.

**Comment by andrewdavey** [comment]
I've copied the issue to the new project: https://github.com/andrewdavey/cassette/issues/3
