### ISSUE TITLE
Knapsack and WebForms

### ISSUE THREAD

**Issue by dustymack** [andrewdavey/knapsack#19]
I am attempting to add Knapsack to an existing application that uses WebForms rather than MVC3.  I see the relevant methods are extensions on the MVC.HtmlHelper class.  Is it possible to use Knapsack in WebForms and, if so, how?

**Comment by andrewdavey** [comment]
The Knapsack project has been renamed (and mostly rewritten) to the new Cassette project: https://github.com/andrewdavey/cassette

Cassette works in both MVC and WebForms. However the documentation isn't all there yet. You can get a sneak preview here http://getcassette.net/

**Comment by dustymack** [comment]
Thank you!
