### ISSUE TITLE
The order in module.txt should have the highest priority

### ISSUE THREAD

**Issue by jochenjonc** [andrewdavey/knapsack#3]
In my Lib folder I have the following script files:

jquery-1.6.1.js
jquery-ui-1.8.13.js
jquery-ui-extra.js
json2.js

This is also the contents of my module.txt file, and I expect it to create a combined script in the same order. But this din't happen, because in my jquery-ui-extra.js file I had the following reference:

/// <reference path="jquery-1.6.1.js" />

Because of that the combined script had the following order:

jquery-ui-1.8.13.js
jquery-1.6.1.js
jquery-ui-extra.js
json2.js

Changing my references solved it, now I have this in my jquery-ui-extra.js file:

/// <reference path="jquery-1.6.1.js" />
/// <reference path="jquery-ui-1.8.13.js" />

But in my opinion the module.txt should be master of the order and shoul ignore the references in the files.

**Comment by andrewdavey** [comment]
I agree, module.txt should override. I'll try to fix this - unless you fancy diving into that code :)
I'm also tempted to support adding a "*" at the end of the file which means "and now everything else in what ever order". This may be useful when a having a folder full of jQuery plugins which only require jQuery to be first.

**Comment by andrewdavey** [comment]
Lastest code in master now uses the order defined in module.txt. Please give it a go and let me know if it's working for you. Thanks!
(I've not added the \* support yet)

**Comment by jochenjonc** [comment]
The order in the module.txt is now working, I can't recreate the bug I had with the new version. 
For me this issue is closed, thx.
