### ISSUE TITLE
Images in stylesheets

### ISSUE THREAD

**Issue by jochenjonc** [andrewdavey/knapsack#4]
In stylesheets you can have the following:

div#header 
{
    background: #325b89 url(images/header-background.png) repeat-x top;
}

The images folder is a relative path starting from the stylesheet itself. But when the stylesheet is minified and combined and called via /knapsack.axd, the relative path isn't correct anymore. Because the image is now search on the following path:

/knapsack.axd/styles/Content/images/header-background.png

A nice feature for knapsack would be that the knapsack.axd returns the image.

**Comment by andrewdavey** [comment]
Thanks for reporting this issue.

Another options is to rewrite the image URL in the CSS to be absolute. Thoughts?

**Comment by jochenjonc** [comment]
For my custom css that is indeed an option, but for the css that came with jQuery UI it is more difficult. Especially when a new theme is rendered via ThemeRoller.

In the end it makes integrating Knapsack a lot easier.

**Comment by andrewdavey** [comment]
Sorry, I meant to say, have Knapsack rewrite the URL to be absolute when it creates the module.

**Comment by andrewdavey** [comment]
I've pushed css url rewriting to master. Can you give it a quick test and let me know if it's working for you.
If everything is good I'll make a new nuget package.

**Comment by jochenjonc** [comment]
Time to make the nuget package, this thing rocks.
