### ISSUE TITLE
Ignore hidden and empty folders

### ISSUE THREAD

**Issue by jochenjonc** [andrewdavey/knapsack#6]
When Knapsack creates the modules and stores them in the isolated storage, more files are created then there modules.

In my case I have files for my .svn folders that are under scripts and styles folder, these are hidden folders and I think they should be ignored all the way. I have also a styles_images_da39a3ee5e6b4b0d3255bfef95601890afd80709 files, this is a folder under the styles folder, that contains the images but no css-files.

These modules can also be found in the manisfest xml-files.

So knapsack should ignore hidden folders and should not create modules for empty folders.

**Comment by andrewdavey** [comment]
Yes, we need to prevent Knapsack from picking up hidden directories.
Ignoring "empty" directories also makes sense and should be an easy fix.
Thanks for the continued beta-testing and excellent feedback! :)

**Comment by andrewdavey** [comment]
I've pushed changes to master. It should now ignore hidden and "empty" directories.

**Comment by jochenjonc** [comment]
Wonderful
